title: Java Oracle - Docker Image
description: Java Oracle (s6-overlay) Docker Image - Extends frekele/debian.
google_analytics: 
show_downloads: true

markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "strikethrough", "superscript", "with_toc_data"]

theme: jekyll-theme-cayman

gems:
  - jekyll-mentions
